Repository WordPress/wporg-developer, pull requests merged in 2023-11, with the labels that each got.

#305 Update chapter list
  source/wp-content/themes/wporg-developer-2023/images/chevron-small.svg
  source/wp-content/themes/wporg-developer-2023/images/dot.svg
  source/wp-content/themes/wporg-developer-2023/src/chapter-list/block.php
  source/wp-content/themes/wporg-developer-2023/src/chapter-list/style.scss
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
  source/wp-content/themes/wporg-developer-2023/templates/single-handbook-github.html
  source/wp-content/themes/wporg-developer-2023/templates/single-handbook.html
  source/wp-content/themes/wporg-developer-2023/theme.json
Labels: Redesign

#335 Be specific about the padding to stop it from growing too large.
  source/wp-content/themes/wporg-developer-2023/js/function-reference.js
  source/wp-content/themes/wporg-developer-2023/src/code-source/style.scss
Labels: Redesign

#337 Add the ability to pass an id to the `code-table`.
  source/wp-content/themes/wporg-developer-2023/src/code-related/block.php
  source/wp-content/themes/wporg-developer-2023/src/code-table/block.json
  source/wp-content/themes/wporg-developer-2023/src/code-table/block.php
  source/wp-content/themes/wporg-developer-2023/src/code-table/style.scss
Labels: Redesign

#346 Remove title edit links from handbooks
  source/wp-content/themes/wporg-developer-2023/functions.php
  source/wp-content/themes/wporg-developer-2023/inc/import-docs.php
Labels: Redesign

#334 Update header behaviour
  source/wp-content/themes/wporg-developer-2023/parts/header-no-breadcrumbs.html
  source/wp-content/themes/wporg-developer-2023/parts/header.html
  source/wp-content/themes/wporg-developer-2023/parts/local-nav.html
  source/wp-content/themes/wporg-developer-2023/patterns/front-page-header.php
  source/wp-content/themes/wporg-developer-2023/templates/front-page.html
Labels: Redesign

#348 Revert "Revert "Update header behaviour""
  source/wp-content/themes/wporg-developer-2023/parts/header-no-breadcrumbs.html
  source/wp-content/themes/wporg-developer-2023/parts/header.html
  source/wp-content/themes/wporg-developer-2023/parts/local-nav.html
  source/wp-content/themes/wporg-developer-2023/patterns/front-page-header.php
  source/wp-content/themes/wporg-developer-2023/templates/front-page.html
Labels: Redesign

#308 Replace `jetpack_require_lib` with a direct file include
  source/wp-content/themes/wporg-developer-2023/inc/cli.php
Labels: [Type] Bug, [Component] Backend, Redesign

#340 Update handbook search bar style
  source/wp-content/themes/wporg-developer-2023/patterns/cli-commands.php
  source/wp-content/themes/wporg-developer-2023/patterns/reference-content.php
  source/wp-content/themes/wporg-developer-2023/patterns/search-field.php
  source/wp-content/themes/wporg-developer-2023/templates/archive.html
  source/wp-content/themes/wporg-developer-2023/templates/taxonomy-wp-parser-since.html
Labels: Redesign

#364 Update handbook wide layout
  source/wp-content/themes/wporg-developer-2023/patterns/article-meta.php
  source/wp-content/themes/wporg-developer-2023/patterns/handbook-pagination.php
  source/wp-content/themes/wporg-developer-2023/src/chapter-list/block.php
  source/wp-content/themes/wporg-developer-2023/src/chapter-list/style.scss
  source/wp-content/themes/wporg-developer-2023/src/chapter-list/view.js
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
  source/wp-content/themes/wporg-developer-2023/templates/single-handbook-github.html
  source/wp-content/themes/wporg-developer-2023/templates/single-handbook.html
  source/wp-content/themes/wporg-developer-2023/theme.json
Labels: Redesign

#351 Fix searchbox autocomplete missing
  source/wp-content/themes/wporg-developer-2023/inc/autocomplete.php
  source/wp-content/themes/wporg-developer-2023/js/autocomplete.js
  source/wp-content/themes/wporg-developer-2023/stylesheets/awesomplete.css
Labels: [Type] Bug, Redesign

#377 Use IBM Plex Sans for headings
  source/wp-content/themes/wporg-developer-2023/patterns/front-page-content.php
  source/wp-content/themes/wporg-developer-2023/patterns/front-page-header.php
  source/wp-content/themes/wporg-developer-2023/patterns/reference-content.php
  source/wp-content/themes/wporg-developer-2023/src/reference-new-updated/block.php
  source/wp-content/themes/wporg-developer-2023/templates/taxonomy-wp-parser-since.html
  source/wp-content/themes/wporg-developer-2023/theme.json
Labels: ui, Redesign

#378 Update front-page-content.php links
  source/wp-content/themes/wporg-developer-2023/patterns/front-page-content.php
Labels: Redesign, [Component] Content

#369 Fix missing Methods section for Class
  source/wp-content/themes/wporg-developer-2023/functions.php
  source/wp-content/themes/wporg-developer-2023/src/code-methods/block.json
  source/wp-content/themes/wporg-developer-2023/src/code-methods/block.php
  source/wp-content/themes/wporg-developer-2023/src/code-methods/index.js
Labels: [Type] Bug, Redesign, [Component] Content

#386 For tables in the content, extend the table full width.
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
Labels: Redesign

#376 Fix accessibility issues with page layouts
  source/wp-content/themes/wporg-developer-2023/parts/search-wide.html
  source/wp-content/themes/wporg-developer-2023/parts/search.html
  source/wp-content/themes/wporg-developer-2023/patterns/cli-commands.php
  source/wp-content/themes/wporg-developer-2023/patterns/reference-content.php
  source/wp-content/themes/wporg-developer-2023/src/chapter-list/block.php
  source/wp-content/themes/wporg-developer-2023/src/command-title/style.scss
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
  source/wp-content/themes/wporg-developer-2023/templates/archive-command.html
  source/wp-content/themes/wporg-developer-2023/templates/archive.html
  source/wp-content/themes/wporg-developer-2023/templates/page-reference.html
  source/wp-content/themes/wporg-developer-2023/templates/single-command.html
  source/wp-content/themes/wporg-developer-2023/templates/single-handbook-github.html
  source/wp-content/themes/wporg-developer-2023/templates/single-handbook.html
  source/wp-content/themes/wporg-developer-2023/templates/single.html
  source/wp-content/themes/wporg-developer-2023/templates/taxonomy-wp-parser-since.html
Labels: [Type] Bug, layout, Accessibility, Redesign

#388 Fix accessibility of GitHub links
  source/wp-content/themes/wporg-developer-2023/functions.php
  source/wp-content/themes/wporg-developer-2023/patterns/article-meta-github.php
  source/wp-content/themes/wporg-developer-2023/patterns/article-meta.php
  source/wp-content/themes/wporg-developer-2023/src/article-meta-github/block.json
  source/wp-content/themes/wporg-developer-2023/src/article-meta-github/block.php
  source/wp-content/themes/wporg-developer-2023/src/article-meta-github/index.js
  source/wp-content/themes/wporg-developer-2023/templates/single-handbook-github.html
Labels: Accessibility, Redesign

#399 Improve the consistency of <title>s
  source/wp-content/themes/wporg-developer-2023/inc/head.php
Labels: Redesign, priority: medium

#381 Add scripts and style to handle toggles in handbook pages
  source/wp-content/themes/wporg-developer-2023/functions.php
  source/wp-content/themes/wporg-developer-2023/js/code-tabs.js
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
Labels: Redesign

#389 Fix accessibility of handbook pagination
  source/wp-content/themes/wporg-developer-2023/functions.php
  source/wp-content/themes/wporg-developer-2023/patterns/handbook-pagination.php
Labels: Accessibility, Redesign

#402 Fix WP-CLI Commands layouts accessibility
  source/wp-content/themes/wporg-developer-2023/functions.php
  source/wp-content/themes/wporg-developer-2023/patterns/cli-commands-content.php
  source/wp-content/themes/wporg-developer-2023/patterns/cli-commands-title.php
  source/wp-content/themes/wporg-developer-2023/patterns/cli-commands.php
  source/wp-content/themes/wporg-developer-2023/src/command-github/block.php
  source/wp-content/themes/wporg-developer-2023/src/command-github/style.scss
  source/wp-content/themes/wporg-developer-2023/templates/single-command.html
Labels: Accessibility, Redesign

#404 Fix broken code block sticky header
  source/wp-content/themes/wporg-developer-2023/scss/prism.scss
  source/wp-content/themes/wporg-developer-2023/stylesheets/prism.css
Labels: [Type] Bug, ui, Redesign, priority: high

#411 Add back <p> tags via wpautop
  source/wp-content/themes/wporg-developer-2023/inc/template-tags.php
Labels: [Type] Bug, Redesign, priority: high
