Repository WordPress/wporg-developer, pull requests merged in 2023-12, with the labels that each got.

#336 Add breadcrumbs to cli/commands.
  source/wp-content/themes/wporg-developer-2023/functions.php
  source/wp-content/themes/wporg-developer-2023/parts/header-no-breadcrumbs.html
  source/wp-content/themes/wporg-developer-2023/parts/header.html
  source/wp-content/themes/wporg-developer-2023/parts/local-nav.html
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
  source/wp-content/themes/wporg-developer-2023/templates/archive-command.html
  source/wp-content/themes/wporg-developer-2023/templates/page-reference.html
  source/wp-content/themes/wporg-developer-2023/templates/taxonomy-wp-parser-since.html
Labels: Redesign

#416 Fix redundant empty result set messages
  source/wp-content/themes/wporg-developer-2023/src/search-results-context/index.php
Labels: Redesign, priority: low

#419 Fix content overflowing code blocks
  source/wp-content/themes/wporg-developer-2023/scss/_global.scss
  source/wp-content/themes/wporg-developer-2023/scss/_reset.scss
  source/wp-content/themes/wporg-developer-2023/scss/main.scss
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
  source/wp-content/themes/wporg-developer-2023/stylesheets/main.css
Labels: [Type] Bug, Redesign, priority: medium

#410 Add styles for comment link modal
  source/wp-content/themes/wporg-developer-2023/functions.php
  source/wp-content/themes/wporg-developer-2023/src/code-comments/block.php
  source/wp-content/themes/wporg-developer-2023/src/editor-style/block.json
  source/wp-content/themes/wporg-developer-2023/src/editor-style/index.js
  source/wp-content/themes/wporg-developer-2023/src/editor-style/style.scss
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
Labels: Redesign, priority: high

#423 Fix the last updated date is not displaying
  source/wp-content/themes/wporg-developer-2023/inc/shortcodes.php
  source/wp-content/themes/wporg-developer-2023/patterns/article-meta.php
Labels: [Type] Bug, Redesign, priority: medium

#425 Fix accessibility scan failures
  source/wp-content/themes/wporg-developer-2023/inc/user-content.php
  source/wp-content/themes/wporg-developer-2023/src/code-short-title/style.scss
  source/wp-content/themes/wporg-developer-2023/src/command-github/style.scss
  source/wp-content/themes/wporg-developer-2023/theme.json
Labels: Accessibility, Redesign, priority: high

#429 Add styles for callouts to match notice blocks
  source/wp-content/themes/wporg-developer-2023/functions.php
  source/wp-content/themes/wporg-developer-2023/images/alert.svg
  source/wp-content/themes/wporg-developer-2023/images/info.svg
  source/wp-content/themes/wporg-developer-2023/images/tip.svg
  source/wp-content/themes/wporg-developer-2023/images/warning.svg
  source/wp-content/themes/wporg-developer-2023/src/code-comments/block.json
  source/wp-content/themes/wporg-developer-2023/src/code-comments/block.php
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
Labels: Redesign

#427 Fix RTL layout
  source/wp-content/themes/wporg-developer-2023/embed.php
  source/wp-content/themes/wporg-developer-2023/patterns/search-field.php
  source/wp-content/themes/wporg-developer-2023/src/chapter-list/style.scss
  source/wp-content/themes/wporg-developer-2023/src/code-comments/style.scss
  source/wp-content/themes/wporg-developer-2023/src/code-parameters/style.scss
  source/wp-content/themes/wporg-developer-2023/src/code-short-title/style.scss
  source/wp-content/themes/wporg-developer-2023/src/command-github/style.scss
  source/wp-content/themes/wporg-developer-2023/src/editor-style/style.scss
  source/wp-content/themes/wporg-developer-2023/src/search-filters/style.scss
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
Labels: Redesign

#430 Remove extra p and a tags from the explanation content
  source/wp-content/themes/wporg-developer-2023/inc/explanations.php
  source/wp-content/themes/wporg-developer-2023/inc/template-tags.php
Labels: [Type] Bug, Redesign, priority: high, Performance, [Component] Content

#435 Modify callout icons and spacing.
  source/wp-content/themes/wporg-developer-2023/images/info.svg
  source/wp-content/themes/wporg-developer-2023/images/tip.svg
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
Labels: [Type] Enhancement, Redesign

#433 Fix/272 block editor handbook code rtl
  source/wp-content/themes/wporg-developer-2023/functions.php
  source/wp-content/themes/wporg-developer-2023/src/prism/block.json
  source/wp-content/themes/wporg-developer-2023/src/prism/index.js
  source/wp-content/themes/wporg-developer-2023/src/prism/style.scss
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
  source/wp-content/themes/wporg-developer-2023/stylesheets/prism.css
Labels: Redesign

#449 Increase banner font-size on Front Page
  source/wp-content/themes/wporg-developer-2023/patterns/front-page-header.php
Labels: [Status] Needs Design Feedback, Redesign

#448 Add blockquote styles
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
Labels: [Type] Enhancement, Redesign

#446 Add redirects for docs changes and update formatting
  source/wp-content/themes/wporg-developer-2023/inc/import-block-editor.php
Labels: [Component] Backend

#457 Add redirect for theme.json doc in the Block Editor Handbook
  source/wp-content/themes/wporg-developer-2023/inc/import-block-editor.php
Labels: [Component] Backend
