Repository WordPress/wporg-developer, pull requests merged in 2024-01, with the labels that each got.

#460 Update typography on home page
  source/wp-content/themes/wporg-developer-2023/patterns/front-page-content.php
  source/wp-content/themes/wporg-developer-2023/theme.json
Labels: Redesign

#459 Fix the paged home page handler 404 response
  source/wp-content/themes/wporg-developer-2023/inc/redirects.php
Labels: [Type] Bug, Redesign

#454 Abstract article meta GitHub for use in different contexts
  source/wp-content/themes/wporg-developer-2023/inc/block-hooks.php
  source/wp-content/themes/wporg-developer-2023/patterns/article-meta.php
  source/wp-content/themes/wporg-developer-2023/src/article-meta-github/block.json
  source/wp-content/themes/wporg-developer-2023/src/article-meta-github/block.php
Labels: Redesign

#462 Remove GitHub handbook last updated date
  source/wp-content/themes/wporg-developer-2023/functions.php
  source/wp-content/themes/wporg-developer-2023/inc/block-hooks.php
  source/wp-content/themes/wporg-developer-2023/patterns/article-meta.php
  source/wp-content/themes/wporg-developer-2023/src/article-meta-date/block.json
  source/wp-content/themes/wporg-developer-2023/src/article-meta-date/block.php
  source/wp-content/themes/wporg-developer-2023/src/article-meta-date/index.js
Labels: Redesign

#468 Code Reference: Related: Fix extra empty links
  source/wp-content/themes/wporg-developer-2023/inc/formatting.php
  source/wp-content/themes/wporg-developer-2023/src/code-related/block.php
Labels: Redesign

#471 Add 'Associated with' information to Explanation editor view
  source/wp-content/themes/wporg-developer-2023/inc/explanations.php
Labels: [Type] Enhancement, Redesign

#472 Fix "Improve it on GitHub" links don't go anywhere if the user is logged out.
  source/wp-content/themes/wporg-developer-2023/inc/shortcodes.php
  source/wp-content/themes/wporg-developer-2023/templates/single.html
Labels: [Type] Bug, Redesign, priority: high

#474 Add a link to LearnWP in the 'Related' section on the front page
  source/wp-content/themes/wporg-developer-2023/patterns/front-page-content.php
Labels: [Type] Enhancement, Redesign

#475 Update UI of Methods section to the table layout used by Related.
  source/wp-content/themes/wporg-developer-2023/src/code-methods/block.php
Labels: [Type] Enhancement, ui, Redesign

#478 Open Graph Meta: Update description and add default image
  source/wp-content/themes/wporg-developer-2023/images/opengraph-image.png
  source/wp-content/themes/wporg-developer-2023/inc/head.php
Labels: [Component] Backend

#486 Fix copy code text twice
  source/wp-content/themes/wporg-developer-2023/js/function-reference.js
Labels: [Type] Bug, Redesign

#469 Chapters and ToC: Internal scroll
  source/wp-content/themes/wporg-developer-2023/patterns/article-sidebar.php
  source/wp-content/themes/wporg-developer-2023/src/chapter-list/style.scss
  source/wp-content/themes/wporg-developer-2023/src/code-comment-form/style.scss
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
  source/wp-content/themes/wporg-developer-2023/templates/single-handbook.html
  source/wp-content/themes/wporg-developer-2023/templates/single.html
Labels: layout, Redesign, priority: high
