Repository WordPress/wporg-developer, pull requests merged in 2024-02, with the labels that each got.

#494 Tools: Update node, yarn, composer packages
  .nvmrc
  composer.lock
  package.json
  source/wp-content/themes/wporg-developer-2023/package.json
  yarn.lock
Labels: [Component] Tools

#491 Update 3 column layout to handle ToC breakpoint changing
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
Labels: layout, Redesign

#501 Remove helper text.
  source/wp-content/themes/wporg-developer-2023/patterns/front-page-content.php
Labels: [Type] Enhancement, Redesign

#499 Improve consistency of layouts
  source/wp-content/themes/wporg-developer-2023/parts/search.html
  source/wp-content/themes/wporg-developer-2023/patterns/cli-commands.php
  source/wp-content/themes/wporg-developer-2023/patterns/single-content.php
  source/wp-content/themes/wporg-developer-2023/src/style/style.scss
  source/wp-content/themes/wporg-developer-2023/templates/archive-command.html
  source/wp-content/themes/wporg-developer-2023/templates/archive.html
  source/wp-content/themes/wporg-developer-2023/templates/search.html
  source/wp-content/themes/wporg-developer-2023/templates/single-command.html
  source/wp-content/themes/wporg-developer-2023/templates/single.html
  source/wp-content/themes/wporg-developer-2023/templates/taxonomy-wp-parser-since.html
  source/wp-content/themes/wporg-developer-2023/theme.json
Labels: layout, Redesign
